apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 5m
#  url: https://istio-release.storage.googleapis.com/charts
  url: https://istio-release.storage.googleapis.com/charts/istio-1.20.0.tgz