apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servicey
  name: servicey
  namespace: servicey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicey
  template:
    metadata:
      labels:
        app: servicey
    spec:
      containers:
        - image: falyoun/cleverbit:s2s-latest
          name: s2s
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi