apiVersion: v1
kind: Service
metadata:
  name: servicey
  namespace: servicey
  labels:
    app: servicey
spec:
  type: ClusterIP
  selector:
    app: servicex
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http