apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authority
  namespace: flux-system
spec:
  interval: 1m0s
  targetNamespace: authority
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: authority
      namespace: default
  path: ./apps/authority
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m